#!/usr/bin/python3

import argparse
import requests
from bs4 import BeautifulSoup
from subprocess import PIPE, Popen


class colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def print_color(string, colorcode):
    print(colorcode + string + colors.ENDC)

def print_red(string):
    print_color(string, colors.RED)

def print_yellow(string):
    print_color(string, colors.YELLOW)

def print_green(string):
    print_color(string, colors.GREEN)

def get_examples(contest_id, problem_code):
    url = 'http://www.codeforces.com/contest/{}/problem/{}'.format(args.contest_id, args.problem_code)
    html = requests.get(url).text

    soup = BeautifulSoup(html, 'lxml')
    inputs = ['\n'.join(chowder.find('pre').strings) for chowder in soup.findAll('div', attrs={'class': 'input'})]
    outputs = ['\n'.join(chowder.find('pre').strings) for chowder in soup.findAll('div', attrs={'class': 'output'})]

    return list(zip(inputs, outputs))


parser = argparse.ArgumentParser()
parser.add_argument('contest_id', type=str)
parser.add_argument('problem_code', type=str)
parser.add_argument('script', type=str)
args = parser.parse_args()

script = args.script

examples = get_examples(args.contest_id, args.problem_code)

for i,t in enumerate(examples):
    i+=1
    ex_input = t[0]
    ex_out = t[1]
    proc = Popen(['python3', script], stdout=PIPE, stderr=PIPE, stdin=PIPE)
    gen_out, err = proc.communicate(ex_input.encode('utf8'))
    gen_out = gen_out.decode('utf8')[:-1]
    err = err.decode('utf8')[:-1]
    if ex_out == gen_out:
        print_green('Example {}: SUCCESS'.format(i))
        print_green('Solution: {}'.format(gen_out))
    else:
        print(ex_input)
        print('Generated:', gen_out)
        print('Actual:   ', ex_out)
        if err:
            print_red('Example {}: ERROR OCCURRED\n{}'.format(i, err))
        else:
            print_red('Example {}: FAILURE'.format(i))
